FROM alonid/rockylinux-rpm-builder:8.6.20227707

RUN yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
RUN yum install -y docker-ce

RUN python3 --version
RUN pip3 install wheel
