# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vast_protobuf/substrait/capabilities.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*vast_protobuf/substrait/capabilities.proto\x12\tsubstrait\"\xfb\x01\n\x0c\x43\x61pabilities\x12\x1a\n\x12substrait_versions\x18\x01 \x03(\t\x12$\n\x1c\x61\x64vanced_extension_type_urls\x18\x02 \x03(\t\x12\x42\n\x11simple_extensions\x18\x03 \x03(\x0b\x32\'.substrait.Capabilities.SimpleExtension\x1a\x65\n\x0fSimpleExtension\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x15\n\rfunction_keys\x18\x02 \x03(\t\x12\x11\n\ttype_keys\x18\x03 \x03(\t\x12\x1b\n\x13type_variation_keys\x18\x04 \x03(\tBW\n\x12io.substrait.protoP\x01Z*github.com/substrait-io/substrait-go/proto\xaa\x02\x12Substrait.Protobufb\x06proto3')



_CAPABILITIES = DESCRIPTOR.message_types_by_name['Capabilities']
_CAPABILITIES_SIMPLEEXTENSION = _CAPABILITIES.nested_types_by_name['SimpleExtension']
Capabilities = _reflection.GeneratedProtocolMessageType('Capabilities', (_message.Message,), {

  'SimpleExtension' : _reflection.GeneratedProtocolMessageType('SimpleExtension', (_message.Message,), {
    'DESCRIPTOR' : _CAPABILITIES_SIMPLEEXTENSION,
    '__module__' : 'vast_protobuf.substrait.capabilities_pb2'
    # @@protoc_insertion_point(class_scope:substrait.Capabilities.SimpleExtension)
    })
  ,
  'DESCRIPTOR' : _CAPABILITIES,
  '__module__' : 'vast_protobuf.substrait.capabilities_pb2'
  # @@protoc_insertion_point(class_scope:substrait.Capabilities)
  })
_sym_db.RegisterMessage(Capabilities)
_sym_db.RegisterMessage(Capabilities.SimpleExtension)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022io.substrait.protoP\001Z*github.com/substrait-io/substrait-go/proto\252\002\022Substrait.Protobuf'
  _CAPABILITIES._serialized_start=58
  _CAPABILITIES._serialized_end=309
  _CAPABILITIES_SIMPLEEXTENSION._serialized_start=208
  _CAPABILITIES_SIMPLEEXTENSION._serialized_end=309
# @@protoc_insertion_point(module_scope)
