# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vast_protobuf/substrait/ddl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vast_protobuf.substrait import plan_pb2 as vast__protobuf_dot_substrait_dot_plan__pb2
from vast_protobuf.substrait import algebra_pb2 as vast__protobuf_dot_substrait_dot_algebra__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!vast_protobuf/substrait/ddl.proto\x12\tsubstrait\x1a\"vast_protobuf/substrait/plan.proto\x1a%vast_protobuf/substrait/algebra.proto\"C\n\x07\x44llPlan\x12,\n\x0binsert_plan\x18\x01 \x01(\x0b\x32\x15.substrait.InsertPlanH\x00\x42\n\n\x08\x64ll_type\"_\n\nInsertPlan\x12\x1e\n\x05input\x18\x01 \x01(\x0b\x32\x0f.substrait.Plan\x12\x31\n\x06output\x18\x02 \x01(\x0b\x32!.substrait.ReadRel.ExtensionTable\"+\n\x03\x44ll\x12$\n\x08\x64ll_plan\x18\x01 \x03(\x0b\x32\x12.substrait.DllPlanB+\n\x12io.substrait.protoP\x01\xaa\x02\x12Substrait.Protobufb\x06proto3')



_DLLPLAN = DESCRIPTOR.message_types_by_name['DllPlan']
_INSERTPLAN = DESCRIPTOR.message_types_by_name['InsertPlan']
_DLL = DESCRIPTOR.message_types_by_name['Dll']
DllPlan = _reflection.GeneratedProtocolMessageType('DllPlan', (_message.Message,), {
  'DESCRIPTOR' : _DLLPLAN,
  '__module__' : 'vast_protobuf.substrait.ddl_pb2'
  # @@protoc_insertion_point(class_scope:substrait.DllPlan)
  })
_sym_db.RegisterMessage(DllPlan)

InsertPlan = _reflection.GeneratedProtocolMessageType('InsertPlan', (_message.Message,), {
  'DESCRIPTOR' : _INSERTPLAN,
  '__module__' : 'vast_protobuf.substrait.ddl_pb2'
  # @@protoc_insertion_point(class_scope:substrait.InsertPlan)
  })
_sym_db.RegisterMessage(InsertPlan)

Dll = _reflection.GeneratedProtocolMessageType('Dll', (_message.Message,), {
  'DESCRIPTOR' : _DLL,
  '__module__' : 'vast_protobuf.substrait.ddl_pb2'
  # @@protoc_insertion_point(class_scope:substrait.Dll)
  })
_sym_db.RegisterMessage(Dll)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022io.substrait.protoP\001\252\002\022Substrait.Protobuf'
  _DLLPLAN._serialized_start=123
  _DLLPLAN._serialized_end=190
  _INSERTPLAN._serialized_start=192
  _INSERTPLAN._serialized_end=287
  _DLL._serialized_start=289
  _DLL._serialized_end=332
# @@protoc_insertion_point(module_scope)
