# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vast_protobuf/substrait/extensions/extensions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3vast_protobuf/substrait/extensions/extensions.proto\x12\x14substrait.extensions\x1a\x19google/protobuf/any.proto\"?\n\x12SimpleExtensionURI\x12\x1c\n\x14\x65xtension_uri_anchor\x18\x01 \x01(\r\x12\x0b\n\x03uri\x18\x02 \x01(\t\"\xef\x04\n\x1aSimpleExtensionDeclaration\x12X\n\x0e\x65xtension_type\x18\x01 \x01(\x0b\x32>.substrait.extensions.SimpleExtensionDeclaration.ExtensionTypeH\x00\x12k\n\x18\x65xtension_type_variation\x18\x02 \x01(\x0b\x32G.substrait.extensions.SimpleExtensionDeclaration.ExtensionTypeVariationH\x00\x12`\n\x12\x65xtension_function\x18\x03 \x01(\x0b\x32\x42.substrait.extensions.SimpleExtensionDeclaration.ExtensionFunctionH\x00\x1aS\n\rExtensionType\x12\x1f\n\x17\x65xtension_uri_reference\x18\x01 \x01(\r\x12\x13\n\x0btype_anchor\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x1a\x66\n\x16\x45xtensionTypeVariation\x12\x1f\n\x17\x65xtension_uri_reference\x18\x01 \x01(\r\x12\x1d\n\x15type_variation_anchor\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x1a[\n\x11\x45xtensionFunction\x12\x1f\n\x17\x65xtension_uri_reference\x18\x01 \x01(\r\x12\x17\n\x0f\x66unction_anchor\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\tB\x0e\n\x0cmapping_type\"j\n\x11\x41\x64vancedExtension\x12*\n\x0coptimization\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12)\n\x0b\x65nhancement\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyBb\n\x12io.substrait.protoP\x01Z5github.com/substrait-io/substrait-go/proto/extensions\xaa\x02\x12Substrait.Protobufb\x06proto3')



_SIMPLEEXTENSIONURI = DESCRIPTOR.message_types_by_name['SimpleExtensionURI']
_SIMPLEEXTENSIONDECLARATION = DESCRIPTOR.message_types_by_name['SimpleExtensionDeclaration']
_SIMPLEEXTENSIONDECLARATION_EXTENSIONTYPE = _SIMPLEEXTENSIONDECLARATION.nested_types_by_name['ExtensionType']
_SIMPLEEXTENSIONDECLARATION_EXTENSIONTYPEVARIATION = _SIMPLEEXTENSIONDECLARATION.nested_types_by_name['ExtensionTypeVariation']
_SIMPLEEXTENSIONDECLARATION_EXTENSIONFUNCTION = _SIMPLEEXTENSIONDECLARATION.nested_types_by_name['ExtensionFunction']
_ADVANCEDEXTENSION = DESCRIPTOR.message_types_by_name['AdvancedExtension']
SimpleExtensionURI = _reflection.GeneratedProtocolMessageType('SimpleExtensionURI', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEEXTENSIONURI,
  '__module__' : 'vast_protobuf.substrait.extensions.extensions_pb2'
  # @@protoc_insertion_point(class_scope:substrait.extensions.SimpleExtensionURI)
  })
_sym_db.RegisterMessage(SimpleExtensionURI)

SimpleExtensionDeclaration = _reflection.GeneratedProtocolMessageType('SimpleExtensionDeclaration', (_message.Message,), {

  'ExtensionType' : _reflection.GeneratedProtocolMessageType('ExtensionType', (_message.Message,), {
    'DESCRIPTOR' : _SIMPLEEXTENSIONDECLARATION_EXTENSIONTYPE,
    '__module__' : 'vast_protobuf.substrait.extensions.extensions_pb2'
    # @@protoc_insertion_point(class_scope:substrait.extensions.SimpleExtensionDeclaration.ExtensionType)
    })
  ,

  'ExtensionTypeVariation' : _reflection.GeneratedProtocolMessageType('ExtensionTypeVariation', (_message.Message,), {
    'DESCRIPTOR' : _SIMPLEEXTENSIONDECLARATION_EXTENSIONTYPEVARIATION,
    '__module__' : 'vast_protobuf.substrait.extensions.extensions_pb2'
    # @@protoc_insertion_point(class_scope:substrait.extensions.SimpleExtensionDeclaration.ExtensionTypeVariation)
    })
  ,

  'ExtensionFunction' : _reflection.GeneratedProtocolMessageType('ExtensionFunction', (_message.Message,), {
    'DESCRIPTOR' : _SIMPLEEXTENSIONDECLARATION_EXTENSIONFUNCTION,
    '__module__' : 'vast_protobuf.substrait.extensions.extensions_pb2'
    # @@protoc_insertion_point(class_scope:substrait.extensions.SimpleExtensionDeclaration.ExtensionFunction)
    })
  ,
  'DESCRIPTOR' : _SIMPLEEXTENSIONDECLARATION,
  '__module__' : 'vast_protobuf.substrait.extensions.extensions_pb2'
  # @@protoc_insertion_point(class_scope:substrait.extensions.SimpleExtensionDeclaration)
  })
_sym_db.RegisterMessage(SimpleExtensionDeclaration)
_sym_db.RegisterMessage(SimpleExtensionDeclaration.ExtensionType)
_sym_db.RegisterMessage(SimpleExtensionDeclaration.ExtensionTypeVariation)
_sym_db.RegisterMessage(SimpleExtensionDeclaration.ExtensionFunction)

AdvancedExtension = _reflection.GeneratedProtocolMessageType('AdvancedExtension', (_message.Message,), {
  'DESCRIPTOR' : _ADVANCEDEXTENSION,
  '__module__' : 'vast_protobuf.substrait.extensions.extensions_pb2'
  # @@protoc_insertion_point(class_scope:substrait.extensions.AdvancedExtension)
  })
_sym_db.RegisterMessage(AdvancedExtension)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022io.substrait.protoP\001Z5github.com/substrait-io/substrait-go/proto/extensions\252\002\022Substrait.Protobuf'
  _SIMPLEEXTENSIONURI._serialized_start=104
  _SIMPLEEXTENSIONURI._serialized_end=167
  _SIMPLEEXTENSIONDECLARATION._serialized_start=170
  _SIMPLEEXTENSIONDECLARATION._serialized_end=793
  _SIMPLEEXTENSIONDECLARATION_EXTENSIONTYPE._serialized_start=497
  _SIMPLEEXTENSIONDECLARATION_EXTENSIONTYPE._serialized_end=580
  _SIMPLEEXTENSIONDECLARATION_EXTENSIONTYPEVARIATION._serialized_start=582
  _SIMPLEEXTENSIONDECLARATION_EXTENSIONTYPEVARIATION._serialized_end=684
  _SIMPLEEXTENSIONDECLARATION_EXTENSIONFUNCTION._serialized_start=686
  _SIMPLEEXTENSIONDECLARATION_EXTENSIONFUNCTION._serialized_end=777
  _ADVANCEDEXTENSION._serialized_start=795
  _ADVANCEDEXTENSION._serialized_end=901
# @@protoc_insertion_point(module_scope)
