# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuf

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A single WHEN x THEN y fragment.
class CaseFragment(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CaseFragment()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCaseFragment(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CaseFragment
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CaseFragment
    def Match(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from vast_flatbuf.org.apache.arrow.computeir.flatbuf.Expression import Expression
            obj = Expression()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CaseFragment
    def Result(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from vast_flatbuf.org.apache.arrow.computeir.flatbuf.Expression import Expression
            obj = Expression()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(2)
def CaseFragmentStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddMatch(builder, match): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(match), 0)
def CaseFragmentAddMatch(builder, match):
    """This method is deprecated. Please switch to AddMatch."""
    return AddMatch(builder, match)
def AddResult(builder, result): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)
def CaseFragmentAddResult(builder, result):
    """This method is deprecated. Please switch to AddResult."""
    return AddResult(builder, result)
def End(builder): return builder.EndObject()
def CaseFragmentEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)