# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tabular

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VipRange(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VipRange()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVipRange(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VipRange
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VipRange
    def StartAddress(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VipRange
    def AddressCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def VipRangeStart(builder):
    builder.StartObject(2)

def Start(builder):
    VipRangeStart(builder)

def VipRangeAddStartAddress(builder, startAddress):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(startAddress), 0)

def AddStartAddress(builder, startAddress):
    VipRangeAddStartAddress(builder, startAddress)

def VipRangeAddAddressCount(builder, addressCount):
    builder.PrependUint16Slot(1, addressCount, 0)

def AddAddressCount(builder, addressCount):
    VipRangeAddAddressCount(builder, addressCount)

def VipRangeEnd(builder):
    return builder.EndObject()

def End(builder):
    return VipRangeEnd(builder)
